
add_newline = true
command_timeout = 2000

format = """$env_var$username$os$hostname$directory$git_branch$git_status
$character
"""

# [character]
# success_symbol = "╰⎯"
# error_symbol = "╰⎯"
# #╭╴ ╰─

# [env_var]
# symbol = "╭╴"
# variable = 'SHELL'
# format = "$symbol"
# disabled = false


# #warp-Drop ugly default prompt characters
# #success_symbol = ""
# #error_symbol = ""

# # ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
NixOS = ' '
Unknown = '󰠥'

# ---y

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user](bold green) ' # 2883ff
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold blue) '
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = '197'
read_only = '  '
format = '[in ](bold white)[$path](bold yellow)[$read_only]($read_only_style) '
style = '#7ed1fb' # yellow bold

