
# import = ["<string>",]
live_config_reload = true

[env]
PENIS = "BIG"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false #true

[scrolling]
history = 10000
multiplier = 3

[font]
builtin_box_drawing = true

[font.normal]
family = "Cascadia Code"
style  = "Normal"
# bold =
# { family = "Cascadia Code"
# , style  = "Bold" }
# italic = 
# { family = "Cascadia Code"
# , style  = "Italic" }
# bold_italic = 
# { family = "Cascadia Code"
# , style  = "Bold Italic" }
# size = 11.25
# offset = 
# { x = 0
# , y = 0 }

[colors.normal]
black   = "#242424"
red     = "#CC241D"
green   = "#98971A"
yellow  = "#FABD2F"
blue    = "#458588"
magenta = "#B16286"
cyan    = "#689D6A"
white   = "#E7D7AD"

[cursor]
style = 
{ shape = "Block"
, blinking = "On" }

[mouse]
hide_when_typing = false
