theme = "cosmic-dark"

[editor]
line-number = "relative"
# cursorline = true
scrolloff = 4
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = [
  #"separator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"

[editor.soft-wrap]
enable = false
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 20
wrap-indicator = ""
# wrap-at-text-width = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.smart-tab]
enable = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
