
[[language]]
name = "markdown"
soft-wrap.enable = true

# [[language]]
# name = "fish"
# language-servers = [ "fish-lsp" ]
# [language-server.fish-lsp]
# command = "fish-lsp start"

# [[languages]]
# name = "nix"
# language-server = [ "nixd", "nil" ]

# [language-server.nixd]
# command = "nixd"
