inherits = "base16_transparent"
"comment" = { fg = "ligh-gray", modifiers = [ "italic", "bold" ] }
"variable" = "light-blue"
"variable.other.member" = "light-blue"
"constant" = "magenta"
"constant.numeric" = "light-magenta"
"type" = "light-red"
"type.builtin" = "magenta"
"keyword" = "red"
"operator" = "magenta"
"function" = "yellow"
"punctuation.special" = "light-magenta"

"ui.cursor" = { fg = "black", bg = "white", modifiers = [""] }
"ui.cursor.primary" = { fg = "black", bg = "white" }
"ui.cursor.match" = { modifiers = [ "reversed" ] }
"ui.bufferline" = { fg = "light-gray" }
"ui.bufferline.active" = { fg = "white" }


# [palette]

