
add_newline = true
command_timeout = 2000

format = """$env_var$username$hostname$directory$git_branch$git_status$cmd_duration
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol =  "[❯](bold red)"
format = '$symbol '

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
NixOS = ''
Unknown = '󰠥'

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user](bold green)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = ' [//](bold white)[ $hostname](bold cyan) '
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = '197'
read_only = '  '
format = '[=> ](bold white)[$path](bold blue)[$read_only]($read_only_style) '

[git_branch]
format = '[$symbol](bold white)[$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = ''
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'
typechanged = ""
style = 'bold red'

[cmd_duration]
format = '󱦟 [$duration](bold yellow) '
