theme = "cosmic-dark"

[editor]
line-number = "relative"
scrolloff = 4
bufferline = "always"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = [
  #"separator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

# [editor.soft-wrap]
# enable = true
# max-wrap = 25 # increase value to reduce forced mid-word wrapping
# max-indent-retain = 0
# wrap-indicator = ""
# wrap-at-text-width = true

[editor.smart-tab]
enable = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
