#! /usr/bin/env bash
set -ueo pipefail

function home {
  case $1 in
    upgrade)
      nix flake update --flake /home/hver/Nix/home-manager
      home-manager switch
      ;;
    *)
      home-manager "$@"
  esac
}

function nixos {
  case $1 in
    upgrade)
      nix flake update --flake /home/hver/Nix/nixos-system
      nixos-rebuild switch
      ;;
    version)
      nixos-version
      ;;
    firewall-tool)
      nixos-firewall-tool "$@"
      ;;
    *)
      nixos-rebuild "$@"
  esac
}

case $1 in
  os)
    shift
    nixos "$@"
    ;;
  home)
    shift
    home "$@"
    ;;
  *)
    nix "$@"
    ;;
esac
