#! /usr/bin/env bash
set -o pipefail
# no `-e` because we check for fails in the build and use that to revert changes.
# no `-u` because there can often be a variable with no value in the script.

function main {
    # Makes sure you aren't running this command as root
    if [[ "$(id -u)" -eq 0 ]]; then
        echo "Do not run this command as root, it will call sudo itself"
        exit 1
    fi

    # Check the arguments and assign the `level` variable accordingly.
    local level
    case $1 in
        "system") level=1 ;;
        "user")   level=3 ;;
        "all")    level=2 ;;
        "")
            echo "no arguments given"
            exit 2
            ;;
        *)
            echo "invalid argument"
            exit 3
            ;;
    esac

    # All values below 3 update the system config.
    if [ $level -lt 3 ]; then
        # Aborts the script if you don't give sudo priviledges
        if sudo true; then true; else
            echo "Aborting upgrade"
            exit 4
        fi
        actions "$NIXOS_REPO" "system"
    fi
    # All values above 1 update the user config.
    if [ $level -gt 1 ]; then
        actions "$HOMEMANAGER_REPO" "user"
    fi
}

# The execution order for the update process.
function actions {
    # Go into the directory containing the flake (needed for git commands).
    cd "$1" || exit 5

    # This checks if you have unsaved changes anywhere and aborts if there are
    # any. Uncomment the below if you want to make sure you don't put any
    # changes out of sync in the git history.
    # changes=$(git diff)
    # if [ "$changes" != "" ]; then
    #     echo "you have unsaved changes in your ${2} config"
    #     return 0
    # fi

    # Checks if anything was actually updated. If not, then exit with a success.
    flakebefore=$(cat flake.lock) # &>/dev/null)
    git pull &>/dev/null
    nix flake update
    flakeafter=$(cat flake.lock) # &>/dev/null)
    if [ "$flakebefore" = "$flakeafter" ]; then
        echo "no updates available for your ${2}"
        return 0
    fi

    # Execute The relevant command.
    case $2 in
        "system") sudo nixos-rebuild switch ;;
        "user") home-manager switch ;;
        *) echo "literally how?"; exit 6
    esac

    # If the updated build failed, then revert the `flake.lock`.
    # Else commit the changes.
    if [ $? -ne 0 ]; then
        git checkout HEAD flake.lock
    else
        git add flake.lock &&
        git commit -m 'updated flake.lock' &&
        git push
    fi
}

main "$@"
